### ISSUE TITLE
Receipt bug

### ISSUE THREAD

**Issue by icerove** [nearprotocol/near-explorer#170] opened 2020-02-07 22:28 UTC
## Acceptance Criteria

- [ ] display correct information on the page
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by frol** [comment] 2020-02-12 21:52
Ouch, I cannot reproduce the issue since the transaction is now part of genesis... :(

Let's close this, but keep track if we see it again.

**Closed by frol** 2020-02-12 21:52 UTC
