### ISSUE TITLE
Show number of online nodes based on telemetry

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#54] opened 2019-07-31 00:14 UTC
We already reporting node telemetry to the end point in explorer - let's show number of online nodes on dashboard.

**Comment by frol** [comment] 2019-07-31 12:53
@ilblackdragon There are no telemetry push calls to the https://explorer.nearcore.com/api/nodes -- I have added the debug output and only see it when I manually trigger the endpoint:

```
$ curl -i -X POST -d 'node_id=frol' -d 'account_id=frol' -d 'latest_block_height=1' https://explorer.nearprotocol.com/api/nodes
```

**Comment by ilblackdragon** [comment] 2019-08-01 01:34
So it's weird, if I do 

--telemetryUrl=http://requestbin.fullcontact.com/1cupqh01

and get this:
```
{"account_id":"","bandwidth_download":57,"bandwidth_upload":5,"cpu":2.607823371887207,"latest_block_hash":"2hWKnXF4T1fYYfcrFzj7F5N1mXSga2hDAskLjExJ5CVo","latest_block_height":1110755,"memory":30788,"node_id":"Ct4gQ3nZvDjHX24dpW8EyoLoeHSosMDi8jYSYZDAUG19","num_peers":5,"signature":"","status":"# 1110755 Downloading headers 100%"}
```

https://requestbin.fullcontact.com/1cupqh01

**Comment by ilblackdragon** [comment] 2019-08-01 01:37
also sending this manually seems weird:
```
curl -d '{"node_id":"frol", "account_id":"frol"}' -H "Content-Type: application/json" -X POST https://explorer.nearprotocol.com/api/nodes
```

**Comment by frol** [comment] 2019-08-02 11:47
@ilblackdragon Your curl command does not include `latest_block_height`, which is the cause for the error (will get it fixed now).

Providing correct data it works fine:

```
$ curl -i -d '{"node_id":"frol", "account_id":"frol", "latest_block_height": 1}' -H "Content-Type: application/json" -X POST https://explorer.nearprotocol.com/api/nodes
```

**Comment by frol** [comment] 2019-08-08 15:36
Resolved with https://github.com/nearprotocol/nearcore/pull/1149

**Closed by frol** 2019-08-08 15:36 UTC
