### ISSUE TITLE
Use tooltip for full precision of balances

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#188] opened 2020-02-19 04:21 UTC
Anywhere where we show NEAR balance, we should add tooltip or click? to show full precision number. 

This is important when we are charging for gas 1e-5 or less it's actually not visible at all. It's important for developers to be able to glean in the full information.

**Comment by frol** [comment] 2020-02-19 16:32
Duplicate of #152

**Closed by frol** 2020-02-19 16:32 UTC
Labels: enhancement
